parameters:
    xidea_person.person.configuration.default.class: Xidea\Bundle\BaseBundle\Configuration
    xidea_person.person.factory.default.class: Xidea\Component\Base\Factory\ModelFactory
  
services:
    xidea_person.person.configuration.default:
        class: %xidea_person.person.configuration.default.class%
        arguments:
            - %xidea_person.person.code%
        tags:
            - { name: xidea_base.configuration }
    xidea_person.person.factory.default:
        class: %xidea_person.person.factory.default.class%
        arguments:
            - %xidea_person.person.class%