parameters:
    xidea_person.template.configuration.default.class: Xidea\Bundle\BaseBundle\Template\TemplateConfiguration
  
services:
    xidea_person.template.configuration.default:
        class: %xidea_person.template.configuration.default.class%
        arguments:
            - %xidea_person.template.namespace%
            - %xidea_person.template.templates%
            - %xidea_person.template.engine%
        calls:
            - [setNamespacedPaths, [%xidea_person.template.namespaced_paths%]]