Xidea\Bundle\PersonBundle\Model\AbstractPerson:
    type: mappedSuperclass
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255